import 'package:shared_preferences/shared_preferences.dart';

class QuoteService {
  static const _key = 'cp_quote_index';

  static const List<String> quotes = [
    'Letakkan sujudmu di awal pagi, maka dunia akan mengikutimu dengan penuh ridha.',
    'Jangan biarkan sibuknya duniamu membuatmu lupa pada siapa yang memberi rezeki.',
    'Kerjakan shalatmu tepat waktu, seolah itu adalah tugas terakhirmu di bumi sebelum menghadap-Nya.',
    'Ketika azan berkumandang, berhentilah sejenak; Allah sedang memanggilmu untuk melipatgandakan rezekimu.',
    'Dahulukan hak Allah di atas segalanya, niscaya urusan kerjamu dipermudah tanpa disangka-sangka.',
    'Sujud di sepertiga malam adalah modal terkuat sebelum melangkah menghadapi kerasnya hari.',
    'Shalat bukan pengganggu pekerjaan, melainkan penenang dan sumber kekuatan utama dalam ikhtiar.',
    'Orang cerdas adalah ia yang menyisihkan waktu dunia demi menghadap Sang Pencipta.',
    'Awali langkah kakimu keluar rumah dengan bismillah dan niat murni mencari ridha-Nya.',
    'Jangan takut tertinggal oleh urusan dunia, karena Allah yang mengatur rezeki hamba yang taat.',
    'Pintu rezeki terbaik terbuka lebar bagi mereka yang menjaga shalatnya di tengah kesibukan.',
    'Hiasi lelahmu dengan dzikir, agar setiap tetes peluh bernilai pahala di sisi-Nya.',
    'Utamakan shalat dhuha sebelum sibuk mengejar dunia, niscaya harimu dipenuhi ketenangan.',
    'Pekerjaan sehebat apa pun akan terasa ringan jika sandaran hatinya hanya kepada Allah.',
    'Jadikan meja kerjamu sebagai sajadah panjang, tempat di mana kejujuran dan amanah ditegakkan.',
    'Saat penat melanda, ingatlah bahwa Allah Maha Mendengar setiap doa di sela kerjamu.',
    'Ibadah adalah bahan bakar utama, dan kerja keras adalah kendaraan untuk sampai pada tujuan-Nya.',
    'Berangkatlah bekerja dengan hati yang bersih, membawa misi ibadah bukan sekadar mencari materi.',
    'Keberkahan kerja bermula dari niat tulus karena Allah, bukan sekadar menggugurkan kewajiban.',
    'Jadikan setiap langkah menuju tempat kerja sebagai saksi kebaikan di akhirat kelak.',
    'Bersyukurlah atas rezeki hari ini, betapa pun sedikitnya, karena dari situlah ketenangan bermula.',
    'Hati yang senantiasa bersyukur tidak akan pernah merasa kekurangan dalam keadaan apa pun.',
    'Rezeki bukan hanya tentang angka di rekening, melainkan tentang ketenangan jiwa yang kau rasakan.',
    'Nikmati prosesnya, syukuri hasilnya, dan serahkan sisanya kepada Sang Maha Pengasih.',
    'Senyumlah pada hari ini, Allah telah menyiapkan rezeki terbaik yang tak akan tertukar.',
    'Berhentilah mengeluh atas lelahmu, karena di setiap peluh terselip ampunan dosa.',
    'Syukur adalah cara terbaik untuk melipatgandakan nikmat yang sudah Allah titipkan.',
    'Jika hatimu merasa sempit, perbanyaklah mengucap alhamdulillah atas nikmat napas yang masih kau miliki.',
    'Rezeki yang disyukuri akan mendatangkan kedamaian yang tak bisa dibeli dengan harta.',
    'Pandanglah apa yang sudah kau miliki hari ini dengan mata penuh rasa syukur yang tulus.',
    'Jangan bandingkan rezekimu dengan milik orang lain, karena porsi kebahagiaan setiap hamba sudah diatur indah.',
    'Syukur mengubah apa yang sedikit menjadi cukup, dan mengubah lelah menjadi berkah.',
    'Hari ini adalah anugerah terindah, sambutlah dengan senyuman dan hati yang lapang.',
    'Terima setiap ketentuan Allah dengan ikhlas, di situlah letak kebahagiaan sejati.',
    'Rezeki yang berkah adalah yang membuatmu semakin dekat kepada Sang Pencipta.',
    'Ketika kau merasa lelah bekerja, ingatlah banyak orang di luar sana yang berdoa demi mendapatkan pekerjaan sepertimu.',
    'Syukuri pagi ini, karena kesehatan dan kesempatan adalah modal utama yang tak ternilai harganya.',
    'Hati yang tenang adalah bukti nyata dari jiwa yang pandai mensyukuri nikmat Tuhan.',
    'Jangan lupa berterima kasih pada diri sendiri dan kepada Allah yang telah menemanimu berjuang.',
    'Rezeki hari ini cukup untuk hidupmu, namun ambisi terkadang membuatmu merasa selalu kurang.',
    'Ikhlaslah dalam bekerja, karena Allah melihat ketulusan niat sekecil apa pun itu.',
    'Usaha maksimal yang dibarengi tawakal tidak akan pernah berbuah sia-sia di mata Allah.',
    'Gagal hari ini adalah cara Allah mengajarkanmu arti kesabaran yang lebih indah.',
    'Pasrahkan hasil akhir kepada Sang Pemilik Semesta, tugasmu hanyalah berikhtiar dengan jujur.',
    'Kejujuran di tempat kerja adalah mahkota seorang hamba yang mencintai Rabb-nya.',
    'Jadikan setiap tantangan kerja sebagai ladang amal untuk mendulang pahala kesabaran.',
    'Rezeki yang halal menenangkan hati, sementara rezeki yang haram membawa gelisah.',
    'Berusahalah dengan tangan terbuka, dan terimalah ketetapan-Nya dengan dada yang lapang.',
    'Tawakal bukan berarti diam berpangku tangan, melainkan berjuang lalu menyerahkan hasilnya pada Yang Kuasa.',
    'Niatkan lelahmu untuk menafkahi keluarga dengan cara yang diridhai-Nya.',
    'Pekerjaan yang dilandasi nilai ibadah tidak akan pernah terasa sebagai beban yang memberatkan.',
    'Kesabaran dalam mencari nafkah adalah bentuk jihad kecil yang sangat dicintai Allah.',
    'Jangan pernah lelah berbuat baik di tempat kerjamu, kebaikan selalu kembali pada pemiliknya.',
    'Harta terbaik adalah yang didapat dengan keringat halal dan dibelanjakan di jalan kebaikan.',
    'Ketenangan jiwa hadir saat seseorang percaya bahwa rezekinya dijamin oleh Yang Maha Kuasa.',
    'Ketika pintu rezeki satu tertutup, Allah telah menyiapkan pintu lain yang jauh lebih baik.',
    'Jadikan kerja kerasmu sebagai bentuk rasa syukur atas nikmat akal dan fisik yang sehat.',
    'Ikhlas menerima hasil ikhtiar adalah tanda kedewasaan spiritual seorang hamba.',
    'Jangan korbankan akhiratmu demi mengejar dunia yang sifatnya hanya sementara.',
    'Setiap tetes keringat ikhlas di jalan kerja adalah penghapus dosa yang tak disadari.',
    'Pagi baru membawa harapan baru, sambutlah dengan semangat ibadah dan senyuman.',
    'Matahari terbit adalah saksi bahwa Allah masih memberimu kesempatan untuk berbuat baik.',
    'Hiruplah udara pagi dengan penuh rasa syukur, hari ini adalah lembaran baru untuk beramal.',
    'Awali langkahmu dengan doa penjemput rezeki, agar harimu dinaungi keberkahan.',
    'Semangat kerjamu hari ini adalah wujud nyata cinta kepada keluarga dan Sang Pencipta.',
    'Biarkan angin pagi menyejukkan hatimu yang bersiap menghadapi kesibukan dunia.',
    'Hari ini adalah kesempatan emas untuk menebar manfaat melalui pekerjaanmu.',
    'Jangan biarkan malas merusak pagimu, karena rezeki terbaik dijemput oleh mereka yang giat.',
    'Secangkir kopi hangat dan doa yang tulus sudah cukup menjadi modal awal yang manis.',
    'Senyuman tulus di tempat kerja adalah sedekah termudah yang membawa kesejukan.',
    'Jadikan tempat kerjamu sebagai taman-taman surga di dunia lewat akhlak yang mulia.',
    'Kemenangan terbesar hari ini adalah saat kau berhasil menjaga hati tetap bersih di tengah keramaian dunia.',
    'Lelahmu hari ini akan berganti menjadi senyuman manis saat malam tiba.',
    'Jangan takut gagal, karena setiap langkah ikhtiar bernilai ibadah di hadapan Allah.',
    'Keindahan hidup terpancar dari hati yang qanaah dan rajin berusaha.',
    'Jadikan kerja kerasmu sebagai bentuk rasa terima kasih atas nikmat hidup yang diberikan.',
    'Ketenangan batin jauh lebih berharga daripada tumpukan harta yang melalaikan.',
    'Berjalanlah dengan penuh keyakinan, Allah membersamai setiap langkah hamba yang ikhlas.',
    'Hari yang melelahkan akan terasa ringan jika diisi dengan dzikir dan niat karena Allah.',
    'Kesuksesan sejati adalah ketika pekerjaan dunia mendekatkanmu pada surga-Nya.',
    'Dunia ini selayaknya persinggahan, maka bekerjalah untuk bekal pulang yang membahagiakan.',
    'Jangan jadikan ambisi dunia sebagai tujuan akhir, jadikan ia jembatan menuju akhirat.',
    'Hati yang damai lahir dari keyakinan bahwa Allah Maha Adil dalam membagi rezeki.',
    'Sembahyanglah sebelum kau disembahyangkan, dan berusahalah seolah kau hidup selamanya.',
    'Harta yang berkah tidak akan membuat pemiliknya sombong, melainkan semakin dermawan.',
    'Kesederhanaan dalam hidup adalah kekayaan hakiki yang menenangkan jiwa.',
    'Pikirkanlah betapa luas rahmat Allah yang selalu mencukupi kebutuhanmu setiap hari.',
    'Jangan biarkan kesibukan dunia merampas waktu sucimu bersama Sang Pencipta.',
    'Kunci kebahagiaan itu sederhana: dekat dengan Allah dan bersyukur atas apa yang ada.',
    'Ketika lelah mendera, ingatlah bahwa peluk hangat keluarga dan ridha Allah menantimu di rumah.',
    'Hidup ini singkat, isilah hari-harimu dengan kerja yang jujur dan ibadah yang khusyuk.',
    'Ketenangan pikiran datang saat kita berhenti mencemaskan hari esok dan fokus beribadah hari ini.',
    'Kemuliaan seseorang terletak pada ketulusan hatinya dalam mencari rezeki yang halal.',
    'Jadikan setiap detik kerjamu bernilai ibadah dengan menghadirkan niat karena Allah.',
    'Rezeki yang berkah tidak pernah salah alamat; ia pasti datang pada waktu yang tepat.',
    'Biarkan hatimu senantiasa bertasbih, meski tanganmu sibuk menyelesaikan tugas dunia.',
    'Kesabaran dalam proses berikhtiar adalah perhiasan terbaik bagi seorang mukmin.',
    'Senja mengajarkan kita untuk ikhlas menutup hari dengan rasa syukur atas segala pencapaian.',
    'Istirahatlah dengan tenang di malam hari, karena Allah yang akan menjaga dunia saat kau tertidur.',
    'Hidup ini indah bagi mereka yang menjadikan setiap usaha sebagai bentuk cinta kepada-Nya.'
  ];

  static Future<String> nextQuote() async {
    final prefs = await SharedPreferences.getInstance();
    final current = prefs.getInt(_key) ?? 0;
    final quote = quotes[current % quotes.length];
    await prefs.setInt(_key, (current + 1) % quotes.length);
    return quote;
  }
}
